src1/accounts/urls.py
from django.conf.urls import patterns, include, url

from . import views

urlpatterns = patterns(
    '',
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),
        name='password-reset-confirm'),
)

src1/my_proj/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import visitors.urls
import profiles.urls
import accounts.urls


from . import views

#urlpatterns = patterns('',
#        url(r'^Vodafone/', include(patterns('wiki.views',
#            url(r'^history/$', 'history'),
#            url(r'^edit/$', 'edit'),
#            url(r'^discuss/$', 'discuss'),
#            url(r'^permissions/$', 'permissions'),
#            ))),
#        )

urlpatterns = patterns('',
        url(r'^$', views.IndexPage.as_view(), name='index'),
        url(r'index.html$', views.IndexPage.as_view(), name='index'),
        url(r'index2.html$', views.Index2Page.as_view(), name='index2'),
	url(r'^admin/', include(admin.site.urls)),
        url(r'^Vodafone/', 
            include([
                url(r'^$', views.HomePage.as_view(), name='home'),
                url(r'^about/$', views.AboutPage.as_view(), name='about'),
                url(r'visitors/', include(visitors.urls, namespace='visitors')),
                url(r'^users/', include(profiles.urls, namespace='profiles')),
                url(r'^admin/', include(admin.site.urls)),
                url(r'^', include(accounts.urls, namespace='accounts')),
                ])),
            )



# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src1/profiles/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = patterns(
    '',
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>\w+)$', views.ShowProfile.as_view(),
        name='show'),
)

src1/visitors/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import ListView

from visitors.models import Visitor, Booking
from visitors import views
from visitors.views import VisitorDetailView

urlpatterns = patterns('',
    url(r'^$', ListView.as_view(model=Visitor, context_object_name="visitor_list", ), name='index'),
    url(r'^bookings/$', ListView.as_view(model=Booking, context_object_name="booking_list", ), name='booking'),
    url(r'^email/$', ListView.as_view(model=Booking, context_object_name="booking_list", ), name='email'),
    url(r'^(?P<pk>\d+)/$', VisitorDetailView.as_view(), name='visitor-detail'),
    #url(r'^(?P<slug>[-_\w]+)/$', VisitorDetailView.as_view(), name='visitor-detail'),
    url(r'^bookings/booking_table_update/$', 'visitors.views.booking_table_update'),
    url(r'^bookings/send_host_request/$', 'visitors.views.send_host_request'    ),
    url(r'^bookings/update_anpr/$', 'visitors.views.update_anpr'    ),
    url(r'^bookings/update_anpr/$', 'visitors.views.update_anpr'    ),
    url(r'^add_booking/$', 'visitors.views.add_booking'             ),
)

src1/templates/_brandname.html
Visitor Management

src1/templates/_navbar.html
<li {% if active_link == "home" %}class="active"{% endif %}><a href="{% url 'home' %}">Home</a></li>
<li {% if active_link == "about" %}class="active"{% endif %}><a href="{% url 'about' %}">About</a></li>

src1/templates/about.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}About{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec1" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>{% include "_brandname.html" %}</h1>
        <p class="lead">An Awesome Tagline Goes Here</p>
      </div>
    </div>
  </div>
</div>

<div id="sec2" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2>Meet The Team</h2>
        <p class="lead">The Wonderful People Behind the Site</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/9/" alt="profile pic"></div>
        <p class="heavy text-center">Cassidy Coder</p>
        <h2>Front-end developer</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/2/" alt="profile pic"></div>
        <p class="heavy text-center">James King</p>
        <h2>CEO</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/1/" alt="profile pic"></div>
        <p class="heavy text-center">Kate Lamport</p>
        <h2>Front-end designer</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
    </div>
    </div>
  </div>
</div>

<div id="sec3">
  <div class="container">
    <div class="row">
      <div id="map-outer" class="col-md-12">
        <div id="address" class="col-md-4">
          <h2>Our Location</h2>
          <address>
            <strong>NetFM Ltd.</strong><br>
            Withycombe<br>
            Crowthorne<br>
            Berkshire<br>
            England<br>
            RG45 7ND<br>
            <abbr>M:</abbr> +44 7830 235500
          </address>
        </div>
        <div id="map-container" class="col-md-8"></div>
      </div>
    </div>
  </div>
</div>
{% endblock container %}

{% block scripts %}
  <script src="https://maps.google.com/maps/api/js?sensor=false"></script>
  <script>

   function init_map() {
     // Enter the latitude and longitude of your office here
	 var myLocation = new google.maps.LatLng(51.369527, -0.796924);

     var mapOptions = {
          center: myLocation,
          zoom: 14
     };

	 var marker = new google.maps.Marker({
	   position: myLocation,
	   title:"We are here"});

     var map = new google.maps.Map(document.getElementById("map-container"),
                                   mapOptions);
	 marker.setMap(map);
   }

   google.maps.event.addDomListener(window, 'load', init_map);
  </script>
{% endblock scripts %}

src1/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load thumbnail %}
    
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Arun Ravindran">
    <meta http-equiv="refresh" content="60">
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

    <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.2/css/bootstrap.min.css" />
    <!--  <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"> -->
    <link href="{% static 'bootstrap-checkbox-x-master/css/checkbox-x.min.css' %}" rel="stylesheet">
    <link href="{% static 'starter-template.css' %}" rel="stylesheet">

    <!-- Custom styles for this site -->
    {% block styles %}
    <link href="{% static 'site/css/main.css' %}" rel="stylesheet">
    {% endblock styles %}

    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    {% block navbar %}
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">
            {% block navbar-brand %}
              <img src="{% static 'site/img/logo.png' %}" alt="logo">
              {% include "_brandname.html" %}
            {% endblock %}
          </a>
        </div>
        {% block navbar-menu %}
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% block navbar-left %}{% endblock %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% block navbar-right %}
              {% if user.is_authenticated %}
                {% if user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle profile-menu" data-toggle="dropdown">
			<img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" alt="" />
			{{ user.get_full_name|truncatechars:20 }}
			<span class="caret"></span>
		    </a>
		    
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'profiles:show_self' %}">Profile</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                  </ul>
                </li>
              {% endif %}
            {% endblock %}
          </ul>
          </ul>
        </div><!--/.nav-collapse -->
        {% endblock %}
    </div>
    {% endblock navbar %}

    {% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock %}

    {% block splash %}
    {% endblock splash %}
    
    {% block container %}
    <div class="container">

      <div class="starter-template">
        <h1>New Project</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->
    {% endblock container %}

    <!-- Site footer -->
    {% block footer %}
      <!-- Some social button for contact will do -->
      <a name="contact"></a>
      <div class="container">
            <div class="footer">
        <div class="row">
          <div class="col-lg-6">
              <p>&copy; NetFM Ltd {% now 'Y' %}</p>
          </div>
          <div class="col-lg-6 text-right">
            Connect with us on
            <a href="#"><i class="fa fa-facebook"></i> Facebook</a> or
            <a href="#"><i class="fa fa-twitter"></i> Twitter</a>
          </div>
        </div>
            </div>
      </div>
    {% endblock %}

    <!-- Bootstrap core JavaScript
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script src="{% static 'bootstrap-checkbox-x-master/js/checkbox-x.min.js' %}"></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

src1/templates/booking_email.html
Subject Line: Your Meeting at {SiteName} - {MeetingDate}
From / Reply-To: Vodafone Travel Team / travel@vodafone.co.uk

<h3>Hi {Firstname},</h3>
<p>
We are pleased to confirm your meeting with {Employee Host Name} at {Building Name}, {Site Name} on {MeetingDate} between {startTime} - {endTime}.
</p>
<p>

Your host has organised Parking for the duration of your visit - please see below for details:
{MeetingDate} - {carParkName}, {spaceID} between {startTime} - {endTime}.
</p>
<p>

There is a 15 minute 'time buffer' before the start and end times of your booking, but please let the <a mailto:"travel@vodafone.co.uk">Vodafone Travel Team</a> know if you are running late and need to adjust the booking, if you cannot attend or decide to use <a href="https://www.click2park.co.uk/Vodafone/visitors/alternative-transport-options.php">alternative transport options</a>.

</p>
<p>
If you need directions to {siteName}, please <a href="https://goo.gl/maps/HuksH">click here for an interactive Map</a>.
</p>
<p>

We look forward to seeing you.
</p>
<p>

Regards
The Vodafone Travel Team.
</p>

src1/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Home{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="home" %}
{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}

{% block splash %}
  <div class="jumbotron jumbotron-carousel corporate-jumbo">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-sm-8">
          <h1>{% include "_brandname.html" %}</h1>
          <p>Complete visitor experience, from booking to departure.</p>
	  <a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
        </div>
        <div class="col-md-4 col-sm-4">

        </div>
      </div>
    </div>
  </div>
{% endblock splash %}

{% block content %}
{% endblock content %}

{% block container %}
<!-- Benefits of the Django application -->
<a name="about"></a>

<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <h2>Visitors</h2>
      <p>Visitors to Vodafone can sign up to request a meeting with a member of Vodafone staff. The meeting will not be scheduled until this booking is confirmed by the member of Vodafone staff hosting the meeting. Visitors will receive confirmation emails, which will also contain public transport details to encourage green travel plans.</p>
      <p><a class="btn btn-primary" href="https://www.click2park.co.uk/Vodafone/visitors/visitor/" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <h2>Employee</h2>
      <p>Vodafone employees can make visitor booking via a single consistemt user interface across all devices. This booking will automatically link to both the car park booking process for visitors and the room booking process. Vodafone employees can pre-register visitors, so their details remain on the system for future visites.</p>
      <p><a class="btn btn-primary" href="https://www.click2park.co.uk/Vodafone/visitors/employee/" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <h2>Reception</h2>
      <p>Vodafone reception can see all current and future visitor bookings. This allows for a seamless meet and greet service, with automated emails and text messages being generated to alert the Vodafone host that their visitor has arrived. The reception can also print lanyard id's directly from tablet devices.</p>
      <p><a class="btn btn-primary" href="{% url 'visitors:booking' %}" role="button">View details &raquo;</a></p>
    </div>
  </div>
</div>

{% endblock container %}

{% block scripts %}
<script src="{% static 'site/js/site.js' %}"></script>
{% endblock scripts %}

src1/templates/index.html
<html>
  <head>
    <meta content="text/html; charset=windows-1252" http-equiv="content-type">
  </head>
  <body>
    <h1 style="text-align: left; margin-top: 0px; height: 0px;"><small><small><small><small><small><a
                  href="map.html">(Back to map page)</a></small></small></small></small></small></h1>
    <h1 style="text-align: center;">This is a record/reminder/log of the stuff
      done</h1>
    <a href="cv.html">CV</a><br>
    <br>
    Retirement is a good time to take a step back and get up to date with stuff
    that's been outstanding for a while. It's also a good time to reflect and
    ascertain how the experience gained over the previous years and the steps
    needed to move forward in the future.<br>
    <br>
    A list of all the things that I need to do:<br>
    <div style="margin-left: 40px;"><a href="Things_to_do.html">Things to do!</a></div>
    <br>
    Always keep up to date this website!<br>
    <div style="margin-left: 40px;"><span style="font-style: italic;">How github
        will control cricket/www/any other information<br>
        Use of diff to compare<br>
        Use of GIT how to update and use on multiple computers<a href="http://www.cyberciti.biz/tips/understanding-unixlinux-symbolic-soft-and-hard-links.html"></a><br>
      </span></div>
    <hr style="width: 100%; height: 2px;"><big>Things that I've looked at:</big><br>
    <br>
    <div style="margin-left: 40px;"><a href="git.html">GIT</a></div>
    <br>
    Shell/Linux script/pages:<br>
    <div style="margin-left: 40px;">ls/ll command:<br>
      <div style="margin-left: 40px;"><a href="ls_ll.html">ls/ll</a><br>
        <a href="symbolic_links.html">Symbolic links</a><br>
        <a href="du.html">du</a></div>
    </div>
    <div style="margin-left: 40px;">Apache:</div>
    <div style="margin-left: 80px;"><a href="apache.html">Apache</a></div>
    <div style="margin-left: 40px;">Makefiles:<br>
      <div style="margin-left: 40px;">Good makefile tutorial <a href="http://mrbook.org/tutorials/make/">Makefiles</a><br>
        Another makefile <a href="http://www.delorie.com/djgpp/doc/ug/larger/makefiles.html">guide</a><br>
        GNU 'make' reference <a href="http://www.gnu.org/software/make/manual/make.html">guide</a><br>
        Makefile target <a href="http://www.stackoverflow.com/questions/9233447/what-is-the-makefile-target-c-o-for">'.c.o'</a></div>
    </div>
    <div style="margin-left: 40px;">Diff</div>
    <div style="margin-left: 40px;">Softlinks</div>
    <a href="mediawiki_tikiwiki.html" target="_top">Website development</a><br>
    <br>
    <a href="cricket.html">Cricket development</a><br>
    <br>
    <a href="C-optimization.html">C optimisation</a><br>
    <br>
    -------------<br>
    Info:<br>
    <a href="http://www.tutorialspoint.com/gsm/gsm_architecture.htm" target="_blank">GSM</a>
    - gives basic background info<br>
    <a href="http://www.tutorialspoint.com/lte/index.htm" target="_blank">LTE</a>
    - not looked at this in any depth<br>
    There are others in this series<br>
    <br>
    <br>
    <a href="speech_codec.html">Speech Codec</a><br>
    <a href="Modulation.html">Modulation</a><br>
    <a href="Real-timeOS.html">Real-time OS</a><br>
    <a href="The_Secret.html">The_Secret</a><br>
    <a href="Energy_bus.html">Energy bus</a>
  </body>
</html>

src1/templates/index2.html
<!DOCTYPE html>
<html>
<head>
	<title>Andrew Carter - Homepage</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<!-- Bootstrap -->
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
	<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet" />

	<link href="http://fonts.googleapis.com/css?family=Abel|Open+Sans:400,600" rel="stylesheet" />

	<style>

		/* http://css-tricks.com/perfect-full-page-background-image/ */
		html {
			background: url(/Vodafone/static/site/img/20150407_195429-1.jpg) no-repeat center center fixed; 
			-webkit-background-size: cover;
			-moz-background-size: cover;
			-o-background-size: cover;
			background-size: cover;
		}

		body {
			padding-top: 20px;
			font-size: 12px;
			font-family: "Open Sans",serif;
			background: transparent;
		}

		h1 {
			font-family: "Abel", Arial, sans-serif;
			font-weight: 400;
			font-size: 36px;
		}

		/* Override B3 .panel adding a subtly transparent background */
		.panel {
			background-color: rgba(255, 255, 255, 0.8);
		}

		.margin-base-vertical {
			margin: 10px 0;
		}

		.margin-base-vertical-40 {
			margin: 10px 0;
		}

	</style>

</head>
<body>

	<div class="container">
		<div class="row">
			<div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 panel panel-default">
				<h1 class="margin-base-vertical">
					Andrew Carter's test website
				</h1>
				<p>
					This website was initially created to try Django with bootstrap3.  
				</p>
				<p>
					It has references from running to work.  
				</p>
				<center><img class="thumbnail profpic" align="middle" width="200" src="/Vodafone/static/site/img/20150408_133719.jpg" alt=""></center>

				<p class="margin-base-vertical-40">
					Please click on the entry button to enter the main site:
				</p>

				<form class="margin-base-vertical">
					<p class="text-center">
						<button type="submit" class="btn btn-primary btn-lg">Enter</button>
						<button type="submit" class="btn btn-success btn-lg">Admin-entry</button>
					</p>
					</span>
				</form>

				<div class="margin-base-vertical">
					<small class="text-muted"><p class="text-center">Background picture Yes Tor - 19:54 7/4/2015</p></small>
				</div>

			</div><!-- //main content -->
		</div><!-- //row -->
	</div> <!-- //container -->

</body>
</html>